-- FR-2: Expected / incoming inventory records (lightweight expected-receipt
-- tracking — explicitly NOT a purchase-order system).
--
-- Adds:
--   * supplier_name_norm(text)  — canonical form used for every supplier match
--   * suppliers                 — curated supplier list, backfilled from the
--                                 distinct shipper names already in the ledger
--   * expected_receipts         — one row per expected delivery (product,
--                                 supplier, qty lb, optional date/reference)
--   * transactions.expected_receipt_id — nullable link set at INSERT time by
--                                 the receiving flow (transactions is
--                                 append-only, so the link is immutable)
--
-- INVARIANT: there is NO stored remaining/received balance anywhere. Remaining
-- is always computed as expected_qty - SUM(posted linked receipt lines) at
-- read time, mirroring the ledger-SUM rule for inventory. Nothing here is read
-- by any on-hand / availability query.
--
-- Forward-safe / idempotent: every statement guards on IF NOT EXISTS or
-- ON CONFLICT DO NOTHING, so a re-run is a no-op.

BEGIN;

-- ── 1. Normalisation function ──────────────────────────────────────────────
-- trim, collapse internal whitespace, straighten curly apostrophes, lowercase.
-- Shared by the unique index below and by main.py's supplier resolver so the
-- DB and the API can never disagree about what "the same supplier" means.
CREATE OR REPLACE FUNCTION public.supplier_name_norm(text)
RETURNS text
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
AS $$
    SELECT lower(
        regexp_replace(
            replace(replace(btrim($1), '’', ''''), '`', ''''),
            '\s+', ' ', 'g'
        )
    )
$$;

-- ── 2. suppliers ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.suppliers (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text        NOT NULL UNIQUE,
    active      boolean     NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT clock_timestamp()
);

-- Case/whitespace-insensitive uniqueness ("Blue Stripes" == "BLUE STRIPES").
CREATE UNIQUE INDEX IF NOT EXISTS suppliers_name_norm_uidx
    ON public.suppliers (public.supplier_name_norm(name));

-- Backfill from every supplier name already present in the ledger:
--   transactions.shipper_name (type = 'receive') and lot_supplier_codes.supplier_name.
-- Names are trimmed / whitespace-collapsed first, then deduplicated on the
-- normalised form; the most frequently used casing wins (ties → alphabetical).
INSERT INTO public.suppliers (name)
SELECT name
FROM (
    SELECT DISTINCT ON (public.supplier_name_norm(name)) name
    FROM (
        SELECT regexp_replace(btrim(shipper_name), '\s+', ' ', 'g') AS name,
               count(*) AS uses
        FROM public.transactions
        WHERE type = 'receive'
          AND btrim(coalesce(shipper_name, '')) <> ''
        GROUP BY 1
        UNION ALL
        SELECT regexp_replace(btrim(supplier_name), '\s+', ' ', 'g') AS name,
               count(*) AS uses
        FROM public.lot_supplier_codes
        WHERE btrim(coalesce(supplier_name, '')) <> ''
        GROUP BY 1
    ) raw_names
    ORDER BY public.supplier_name_norm(name), uses DESC, name
) deduped
ON CONFLICT DO NOTHING;

-- ── 3. expected_receipts ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.expected_receipts (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       integer        NOT NULL REFERENCES public.products(id),
    supplier_id      integer        NOT NULL REFERENCES public.suppliers(id),
    expected_qty     numeric(14,4)  NOT NULL CHECK (expected_qty > 0),   -- lb
    expected_date    date,
    reference_number text,
    notes            text,
    status           text           NOT NULL DEFAULT 'open'
                     CHECK (status IN ('open', 'closed', 'cancelled')),
    created_at       timestamptz    NOT NULL DEFAULT clock_timestamp(),
    created_by       text,
    updated_at       timestamptz    NOT NULL DEFAULT clock_timestamp()
);

-- Auto-match lookup in the receiving flow: open rows for (product, supplier),
-- FIFO on expected_date.
CREATE INDEX IF NOT EXISTS idx_expected_receipts_open_match
    ON public.expected_receipts (product_id, supplier_id, expected_date, id)
    WHERE status = 'open';

CREATE INDEX IF NOT EXISTS idx_expected_receipts_status_date
    ON public.expected_receipts (status, expected_date);

-- ── 4. Link column on the receiving ledger table ───────────────────────────
-- Receiving posts write one `transactions` row (type = 'receive', carries
-- shipper_name/bol_reference) plus its transaction_lines. The link lives on
-- the transaction header; quantities are still read from the lines.
ALTER TABLE public.transactions
    ADD COLUMN IF NOT EXISTS expected_receipt_id integer
        REFERENCES public.expected_receipts(id);

CREATE INDEX IF NOT EXISTS idx_transactions_expected_receipt
    ON public.transactions (expected_receipt_id)
    WHERE expected_receipt_id IS NOT NULL;

COMMIT;
