-- Supplies feature (dashboard-only): packaging + consumables inventory view,
-- per-product low-stock thresholds, and a lightweight supply-request queue.
--
-- Adds:
--   * products.type CHECK      — the product "category" lives in products.type
--                                (text + CHECK constraint, NOT an enum). It is
--                                widened to admit 'consumable'. 'packaging' was
--                                already allowed (32 live rows) and is kept.
--   * products.low_stock_threshold — nullable NUMERIC, ANY category
--                                (ingredients included). NULL = no alerting.
--                                Read only by GET /supplies/inventory (is_low).
--   * supply_requests          — one row per "we need X" request. Either a
--                                product_id OR free-text item_text, never both,
--                                never neither. status open -> done only.
--
-- INVARIANT: nothing here stores a balance. on_hand / is_low are computed at
-- read time as the posted-only ledger SUM (same rule as every other on-hand
-- figure). low_stock_threshold is a comparison input, not a cached quantity.
--
-- Forward-safe / idempotent: IF NOT EXISTS / DROP-then-ADD on named
-- constraints, so a re-run is a no-op.

BEGIN;

-- ── 1. products.type: admit 'consumable' (keep every existing value) ────────
-- pg_dump name of the live constraint is products_type_check; re-create it
-- with the widened list. Same statement shape as 040 (pack_format check).
ALTER TABLE public.products DROP CONSTRAINT IF EXISTS products_type_check;
ALTER TABLE public.products
    ADD CONSTRAINT products_type_check
    CHECK (type = ANY (ARRAY['ingredient'::text, 'packaging'::text, 'batch'::text,
                             'finished'::text, 'consumable'::text]));

-- ── 2. products.low_stock_threshold ────────────────────────────────────────
ALTER TABLE public.products
    ADD COLUMN IF NOT EXISTS low_stock_threshold numeric;

ALTER TABLE public.products DROP CONSTRAINT IF EXISTS products_low_stock_threshold_check;
ALTER TABLE public.products
    ADD CONSTRAINT products_low_stock_threshold_check
    CHECK (low_stock_threshold IS NULL OR low_stock_threshold >= 0);

COMMENT ON COLUMN public.products.low_stock_threshold IS
    'Alert when posted-only on-hand < this value (product uom). NULL = no alerting. Applies to every product type.';

-- ── 3. supply_requests ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.supply_requests (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    integer      REFERENCES public.products(id),
    item_text     text,
    qty           numeric,
    note          text,
    requested_by  text         NOT NULL,
    status        text         NOT NULL DEFAULT 'open'
                  CONSTRAINT supply_requests_status_check CHECK (status IN ('open', 'done')),
    created_at    timestamptz  NOT NULL DEFAULT clock_timestamp(),
    done_at       timestamptz,
    -- exactly one of product_id / item_text
    CONSTRAINT supply_requests_target_xor_check
        CHECK ((product_id IS NULL) <> (item_text IS NULL)),
    CONSTRAINT supply_requests_item_text_nonblank_check
        CHECK (item_text IS NULL OR btrim(item_text) <> ''),
    CONSTRAINT supply_requests_qty_check
        CHECK (qty IS NULL OR qty > 0),
    -- done_at is set exactly when status = 'done'
    CONSTRAINT supply_requests_done_at_check
        CHECK ((status = 'done') = (done_at IS NOT NULL))
);

-- Dashboard list is "open first, newest first"; product filter for lookups.
CREATE INDEX IF NOT EXISTS idx_supply_requests_status_created
    ON public.supply_requests (status, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_supply_requests_product
    ON public.supply_requests (product_id)
    WHERE product_id IS NOT NULL;

COMMIT;
