-- Sales-order allocations (FR-4, PR 1 of the allocation/readiness design —
-- docs/designs/044-so-allocations-design.md). SCHEMA ONLY. Zero behavior:
-- no endpoint, helper, or ship-path change reads or writes this table yet.
--
-- One row per exclusive finished-goods reservation slice against an SO line:
--   * lot_id IS NULL  → SKU-level reservation (ordinary demand)
--   * lot_id NOT NULL → lot-level pin (staged / auto-FIFO / ship-legal lot)
-- "Live" = status = 'active' (readers additionally honour expires_at for
-- auto_fifo rows; that is a read-time predicate, not a column state).
--
-- INVARIANTS (enforced by the handlers in later PRs, not here):
--   * on-hand / over-allocation is NEVER stored — the ledger is a view over
--     corrections, so SUM(active) <= posted on-hand cannot be a CHECK.
--   * product match (soa.product_id = sol.product_id; lots.product_id = soa.product_id
--     when lot_id is set) is enforced in the allocate handler (no composite FK
--     exists on (lots.id, lots.product_id) that we want to add here).
--   * status transitions (active -> released | shipped | superseded, and
--     void/restore coalescing onto a live leftover row) are handler logic.
--
-- UNIQUE LIVE INDEXES — keep these; do not drop them:
--   at most ONE live SKU-level row per line, and ONE live pin per (line, lot).
--   Allocate upserts. Partial ship SPLITS (leftover stays the sole live row).
--   Void of a partial ship COALESCES onto the leftover — it must never INSERT a
--   second live row for the same key.
--
-- No business_date column. No session-level GUCs. Idempotent (IF NOT EXISTS
-- everywhere) so a re-run is a no-op.

BEGIN;

CREATE TABLE IF NOT EXISTS public.sales_order_allocations (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id           integer NOT NULL REFERENCES public.sales_orders(id),
    sales_order_line_id      integer NOT NULL REFERENCES public.sales_order_lines(id),
    product_id               integer NOT NULL REFERENCES public.products(id),
    lot_id                   integer REFERENCES public.lots(id),            -- NULL = SKU-level
    quantity_lb              numeric(14,4) NOT NULL
                             CONSTRAINT soa_quantity_lb_check CHECK (quantity_lb > 0),
    status                   text NOT NULL DEFAULT 'active'
                             CONSTRAINT soa_status_check
                             CHECK (status IN ('active', 'released', 'shipped', 'superseded')),
    source                   text NOT NULL
                             CONSTRAINT soa_source_check
                             CHECK (source IN ('manual', 'auto_fifo', 'staged_lot')),
    ship_transaction_id      integer REFERENCES public.transactions(id),    -- set iff status = 'shipped'
    last_ship_transaction_id integer REFERENCES public.transactions(id),    -- retained across void/restore
    split_from_id            bigint REFERENCES public.sales_order_allocations(id), -- original row of a split_on_ship
    created_at               timestamptz NOT NULL DEFAULT clock_timestamp(),
    created_at_source        text NOT NULL DEFAULT 'database',
    -- Interim FR-15 attribution convention (see caller_source_tag() in main.py
    -- and expected_receipts.created_by): a plain SOURCE tag such as
    -- 'dashboard' / 'gpt-sales-admin', NULL when unknown — never the
    -- 'legacy-shared-key' operator placeholder.
    created_by               text,
    released_at              timestamptz,
    released_by              text,
    release_reason           text,
    expires_at               timestamptz,                                    -- NULL = no TTL; auto_fifo only
    note                     text,
    CONSTRAINT allocations_shipped_has_txn
        CHECK ((status = 'shipped') = (ship_transaction_id IS NOT NULL)),
    CONSTRAINT allocations_released_has_time
        CHECK ((status <> 'released') OR (released_at IS NOT NULL))
);

-- One live SKU-level slice per line.
CREATE UNIQUE INDEX IF NOT EXISTS soa_active_sku_uniq
    ON public.sales_order_allocations (sales_order_line_id)
    WHERE status = 'active' AND lot_id IS NULL;

-- One live pin per (line, lot). Two DIFFERENT lines may pin the same lot
-- (partial lots across orders) — uniqueness is per line.
CREATE UNIQUE INDEX IF NOT EXISTS soa_active_lot_uniq
    ON public.sales_order_allocations (sales_order_line_id, lot_id)
    WHERE status = 'active' AND lot_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS soa_active_product_idx
    ON public.sales_order_allocations (product_id)
    WHERE status = 'active';

CREATE INDEX IF NOT EXISTS soa_active_lot_idx
    ON public.sales_order_allocations (lot_id)
    WHERE status = 'active' AND lot_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS soa_order_idx
    ON public.sales_order_allocations (sales_order_id);

CREATE INDEX IF NOT EXISTS soa_ship_txn_idx
    ON public.sales_order_allocations (ship_transaction_id)
    WHERE ship_transaction_id IS NOT NULL;

COMMENT ON TABLE public.sales_order_allocations IS
    'Exclusive FG reservation against an SO line. lot_id NULL = SKU-level. Live = status active; one live SKU row per line, one live pin per (line, lot).';
COMMENT ON COLUMN public.sales_order_allocations.lot_id IS
    'NULL = SKU-level reservation; NOT NULL = lot-level pin.';
COMMENT ON COLUMN public.sales_order_allocations.status IS
    'active | released | shipped | superseded. shipped <=> ship_transaction_id set; released requires released_at.';
COMMENT ON COLUMN public.sales_order_allocations.source IS
    'manual | auto_fifo | staged_lot. Never overwritten by void/restore.';
COMMENT ON COLUMN public.sales_order_allocations.expires_at IS
    'Optional TTL (auto_fifo only). Readers treat expired rows as not live; status flips to released on the next write.';

COMMIT;
