-- Trace tables (TRACEABILITY_DESIGN.md §3.2/§3.3, migration plan §9 step 2)
-- — schema ONLY: no emission code, no main.py changes. Deploys inert: zero
-- rows until step 3 (emission hooks) lands.
--
--   * trace_events — one row per physical event (§3.2). occurred_at is the
--     claimed physical time (CC-3); recorded_at is DB-owned entry time,
--     trigger-enforced like created_at; late_recorded is a generated flag at
--     the 24 h threshold (tunable later by one DROP/ADD COLUMN, data-free).
--   * trace_event_lots — the lots an event touched, with roles and the
--     transaction_lines sign convention (§3.3).
--   * Both tables get the standard 039 protections: created_at enforcement
--     (ledger_enforce_created_at) and append-only (ledger_block_append_only_
--     change) triggers. ledger_enforce_created_at is REPLACED below (same
--     move as 046) to add the 'trace_backfill_048' provenance carve-out for
--     the §9 step-4 backfill: only rows carrying that marker may keep it and
--     may supply a historical recorded_at (reconstructed from created_at
--     where created_at_source='database', else legacy "timestamp" — the 039
--     backfill stamped created_at with the migration time, so using it
--     blindly would mark 500+ historical rows falsely late). created_at
--     itself stays database-owned for every insert, marker or not.
--   * trace_events_txn_type_uniq is UNIQUE NULLS NOT DISTINCT (PG 15+; prod
--     is 17.6): with default null semantics the constraint would be vacuous
--     for every non-correction event (correction_id NULL never conflicts),
--     letting a double-fired emission hook insert duplicate receive/make/
--     pack/ship/adjust events — the exact bug this constraint exists to
--     catch. Void/restore/amend events carry distinct correction_ids and are
--     unaffected.
--
-- Idempotent (IF NOT EXISTS / CREATE OR REPLACE / DROP TRIGGER IF EXISTS) so
-- a re-run is a no-op.

BEGIN;

-- 1. trace_events — one row per physical event (§3.2).
CREATE TABLE IF NOT EXISTS public.trace_events (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_uuid        uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    -- what happened (domain verb) and its EPCIS classification
    event_type        text NOT NULL CHECK (event_type IN
                        ('receive','make','pack','ship','adjust','void','restore','amend','merge')),
    epcis_type        text NOT NULL CHECK (epcis_type IN ('object','transformation','aggregation')),
    -- provenance: the operational transaction that emitted this event
    transaction_id    integer NOT NULL REFERENCES public.transactions(id),
    correction_id     uuid REFERENCES public.ledger_corrections(id),   -- set for void/restore/amend events
    -- time (CC-3)
    occurred_at       timestamptz NOT NULL,   -- copied from transactions.occurred_at (claimed physical time)
    recorded_at       timestamptz NOT NULL DEFAULT clock_timestamp(),  -- DB-owned, trigger-enforced
    business_date     date NOT NULL,
    late_recorded     boolean GENERATED ALWAYS AS
                        ((recorded_at - occurred_at) > interval '24 hours') STORED,
    -- parties and place (free text mirrors the operational row; FKs where they exist)
    biz_location      text NOT NULL DEFAULT 'seven-wells-plant',
    source_party      text,          -- receive: shipper_name
    destination_party text,          -- ship: customer_name
    customer_id       integer REFERENCES public.customers(id),   -- when resolvable (SO-ship path)
    sales_order_id    integer REFERENCES public.sales_orders(id),
    operator_id       text,
    created_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
    created_at_source text NOT NULL DEFAULT 'database',
    CONSTRAINT trace_events_correction_pairing CHECK
        ((event_type IN ('void','restore','amend')) = (correction_id IS NOT NULL)),
    CONSTRAINT trace_events_txn_type_uniq
        UNIQUE NULLS NOT DISTINCT (transaction_id, event_type, correction_id)
);

CREATE INDEX IF NOT EXISTS trace_events_txn_idx
    ON public.trace_events (transaction_id);
CREATE INDEX IF NOT EXISTS trace_events_occurred_idx
    ON public.trace_events (occurred_at);
CREATE INDEX IF NOT EXISTS trace_events_late_idx
    ON public.trace_events (business_date) WHERE late_recorded;

COMMENT ON COLUMN public.trace_events.recorded_at IS
    'Database-owned entry time, trigger-enforced to clock_timestamp(); only '
    'rows inserted with created_at_source=trace_backfill_048 may supply the '
    'historical entry time the §9 step-4 backfill reconstructs.';
COMMENT ON COLUMN public.trace_events.late_recorded IS
    'Generated: recorded more than 24 h after it occurred. Threshold change '
    '= one DROP/ADD COLUMN, data-free (TRACEABILITY_DESIGN.md §3.2).';

-- 2. trace_event_lots — the lots an event touched, with roles (§3.3).
--    Sign convention: positive = into the lot (output/received), negative =
--    out of it (input/shipped); 'adjusted'/'moved' may be either sign;
--    matches transaction_lines.
CREATE TABLE IF NOT EXISTS public.trace_event_lots (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_event_id  bigint NOT NULL REFERENCES public.trace_events(id),
    lot_id          integer NOT NULL REFERENCES public.lots(id),
    role            text NOT NULL CHECK (role IN
                      ('input','output','shipped','received','adjusted','moved')),
    quantity_lb     numeric(14,4) NOT NULL CHECK (quantity_lb <> 0),
    created_at        timestamptz NOT NULL DEFAULT clock_timestamp(),
    created_at_source text NOT NULL DEFAULT 'database',
    CONSTRAINT tel_role_sign CHECK (
        (role IN ('output','received') AND quantity_lb > 0)
     OR (role IN ('input','shipped')  AND quantity_lb < 0)
     OR (role IN ('adjusted','moved'))
    ),
    CONSTRAINT tel_event_lot_role_uniq UNIQUE (trace_event_id, lot_id, role)
);

CREATE INDEX IF NOT EXISTS tel_lot_idx
    ON public.trace_event_lots (lot_id);
CREATE INDEX IF NOT EXISTS tel_lot_role_idx
    ON public.trace_event_lots (lot_id, role);

-- 3. Provenance carve-out for the §9 step-4 backfill — same move as 046's
--    api_backfill carve-out: replace the shared enforcement function with the
--    new table/marker pair added. Attached to every 039 ledger table, so the
--    logic below must keep the transactions behavior byte-identical.
CREATE OR REPLACE FUNCTION public.ledger_enforce_created_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        -- Entry time remains database-owned. Only the known provenance
        -- markers are caller-selectable, each on its own tables:
        -- 'api_backfill' for transaction backfills (046) and
        -- 'trace_backfill_048' for the trace-layer backfill (048).
        NEW.created_at := clock_timestamp();
        IF NOT (
            (TG_TABLE_NAME = 'transactions'
                AND NEW.created_at_source IS NOT DISTINCT FROM 'api_backfill')
            OR (TG_TABLE_NAME IN ('trace_events', 'trace_event_lots')
                AND NEW.created_at_source IS NOT DISTINCT FROM 'trace_backfill_048')
        ) THEN
            NEW.created_at_source := 'database';
        END IF;
        IF TG_TABLE_NAME = 'transactions' THEN
            NEW.entry_backfilled := NEW.created_at_source = 'api_backfill';
        END IF;
        IF TG_TABLE_NAME = 'trace_events'
           AND NEW.created_at_source IS DISTINCT FROM 'trace_backfill_048' THEN
            -- recorded_at is DB-owned (§3.2); only the marked backfill may
            -- supply the historical entry time it reconstructs.
            NEW.recorded_at := clock_timestamp();
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.created_at IS DISTINCT FROM OLD.created_at
       OR NEW.created_at_source IS DISTINCT FROM OLD.created_at_source THEN
        RAISE EXCEPTION 'created_at and created_at_source are immutable on %', TG_TABLE_NAME
            USING ERRCODE = '23000';
    END IF;
    RETURN NEW;
END;
$$;

-- 4. 039-pattern protections on both tables.
DROP TRIGGER IF EXISTS trg_trace_events_created_at ON public.trace_events;
CREATE TRIGGER trg_trace_events_created_at
BEFORE INSERT OR UPDATE ON public.trace_events
FOR EACH ROW EXECUTE FUNCTION ledger_enforce_created_at();
DROP TRIGGER IF EXISTS trg_trace_events_append_only ON public.trace_events;
CREATE TRIGGER trg_trace_events_append_only
BEFORE UPDATE OR DELETE ON public.trace_events
FOR EACH ROW EXECUTE FUNCTION ledger_block_append_only_change();

DROP TRIGGER IF EXISTS trg_trace_event_lots_created_at ON public.trace_event_lots;
CREATE TRIGGER trg_trace_event_lots_created_at
BEFORE INSERT OR UPDATE ON public.trace_event_lots
FOR EACH ROW EXECUTE FUNCTION ledger_enforce_created_at();
DROP TRIGGER IF EXISTS trg_trace_event_lots_append_only ON public.trace_event_lots;
CREATE TRIGGER trg_trace_event_lots_append_only
BEFORE UPDATE OR DELETE ON public.trace_event_lots
FOR EACH ROW EXECUTE FUNCTION ledger_block_append_only_change();

COMMIT;
