-- AI-assisted expected-receipt intake (docs/designs/expected-receipt-intake.md).
--
-- Adds:
--   * purchase_documents        — one row per uploaded vendor PO / order
--                                 confirmation (Supabase Storage object +
--                                 validated extraction JSON for audit)
--   * supplier_product_aliases  — supplier's wording → our product, learned on
--                                 approval (latest approval wins); checked
--                                 BEFORE any fuzzy match
--   * expected_receipts.source_document_id — link from each created receipt to
--                                 its source document
--   * dedupe index on (supplier_id, normalized reference_number) — warn-only
--                                 lookup, deliberately NOT a unique constraint
--
-- INVARIANT: nothing here is read by any inventory balance / availability
-- query. The stored `extraction` JSON is audit-only — matching and approval
-- always run against live products/suppliers/aliases, never the stored blob.
--
-- Forward-safe: the CREATE/ALTER statements guard on IF NOT EXISTS and the
-- resulting schema is identical on every run (idempotent end state). A
-- re-run is NOT a pure no-op, though: the status CHECK constraint below is
-- dropped and re-added by name on every run, which re-VALIDATES it against
-- all existing purchase_documents rows and briefly takes an ACCESS
-- EXCLUSIVE lock on the table.

BEGIN;

-- ── 1. purchase_documents ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.purchase_documents (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_bucket    text        NOT NULL DEFAULT 'purchase-documents',
    storage_path      text        NOT NULL UNIQUE,
    original_filename text,
    mime_type         text        NOT NULL
                      CHECK (mime_type IN ('image/png','image/jpeg','application/pdf')),
    file_sha256       text        NOT NULL,
    byte_size         integer     NOT NULL CHECK (byte_size > 0),
    extraction        jsonb,
    extraction_model  text,
    status            text        NOT NULL DEFAULT 'uploaded'
                      CHECK (status IN ('uploaded','upload_failed','extracted','extraction_failed','approved')),
    approved_at       timestamptz,
    uploaded_at       timestamptz NOT NULL DEFAULT clock_timestamp(),
    created_by        text
);

-- Audit fix 12: 'upload_failed' marks a row whose Storage write failed (no
-- object behind it — re-upload, don't retry extraction). Named-constraint
-- replacement so a re-run upgrades a table created by an earlier draft of
-- this migration; on a fresh table it drops and re-adds the same constraint.
ALTER TABLE public.purchase_documents
    DROP CONSTRAINT IF EXISTS purchase_documents_status_check;
ALTER TABLE public.purchase_documents
    ADD CONSTRAINT purchase_documents_status_check
    CHECK (status IN ('uploaded','upload_failed','extracted','extraction_failed','approved'));

-- Re-upload detection ("already_seen" in the extract response).
CREATE INDEX IF NOT EXISTS idx_purchase_documents_sha256
    ON public.purchase_documents (file_sha256);

-- ── 2. supplier_product_aliases ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.supplier_product_aliases (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id        integer       NOT NULL REFERENCES public.suppliers(id),
    vendor_description text          NOT NULL,
    product_id         integer       NOT NULL REFERENCES public.products(id),
    lb_per_unit        numeric(14,4) CHECK (lb_per_unit > 0),
    unit               text,
    created_at         timestamptz   NOT NULL DEFAULT clock_timestamp(),
    created_by         text,
    updated_at         timestamptz   NOT NULL DEFAULT clock_timestamp()
);

-- One alias per (supplier, normalized vendor wording); approval upserts onto
-- this index (ON CONFLICT DO UPDATE — latest approved correction wins).
CREATE UNIQUE INDEX IF NOT EXISTS supplier_product_aliases_uidx
    ON public.supplier_product_aliases
    (supplier_id, lower(regexp_replace(btrim(vendor_description), '\s+', ' ', 'g')));

-- ── 3. Link column on expected_receipts ────────────────────────────────────
ALTER TABLE public.expected_receipts
    ADD COLUMN IF NOT EXISTS source_document_id integer
        REFERENCES public.purchase_documents(id);

CREATE INDEX IF NOT EXISTS idx_expected_receipts_source_doc
    ON public.expected_receipts (source_document_id)
    WHERE source_document_id IS NOT NULL;

-- ── 4. Dedupe lookup ───────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_expected_receipts_supplier_ref
    ON public.expected_receipts (supplier_id,
        lower(regexp_replace(btrim(reference_number), '\s+', ' ', 'g')))
    WHERE reference_number IS NOT NULL;

COMMIT;
