-- 050: Sales-order document intake (docs/designs/sales-order-intake.md)
--
-- Generalizes the ER intake pipeline (migration 049) to customer POs:
--   * purchase_documents.document_kind ('purchase' | 'sales') — one pipeline,
--     no second table.
--   * customer_product_aliases — the customer's wording → our product,
--     learned on approval, latest wins. alias_key (item code if present,
--     else description, normalized) gives one unambiguous ON CONFLICT target.
--   * sales_orders.customer_po + source_document_id, with a warn-only dedupe
--     index on (customer_id, normalized customer_po).
--
-- Deploy order (row-117 precedent): apply to prod via session pooler 5432
-- BEFORE merging/deploying code that reads the new columns; then re-dump
-- tests/schema/schema.sql via scripts/dump_prod_schema.sh.

BEGIN;

ALTER TABLE public.purchase_documents
    ADD COLUMN IF NOT EXISTS document_kind text NOT NULL DEFAULT 'purchase'
        CHECK (document_kind IN ('purchase', 'sales'));
CREATE INDEX IF NOT EXISTS idx_purchase_documents_kind
    ON public.purchase_documents (document_kind);

CREATE TABLE IF NOT EXISTS public.customer_product_aliases (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id          integer NOT NULL REFERENCES public.customers(id),
    customer_item_code   text,
    customer_description text,
    product_id           integer NOT NULL REFERENCES public.products(id),
    case_size_lb         numeric(14,4) CHECK (case_size_lb > 0),
    created_at           timestamptz NOT NULL DEFAULT clock_timestamp(),
    created_by           text,
    updated_at           timestamptz NOT NULL DEFAULT clock_timestamp(),
    alias_key            text GENERATED ALWAYS AS
        (lower(regexp_replace(btrim(coalesce(customer_item_code, customer_description)),
                              '\s+', ' ', 'g'))) STORED,
    CHECK (customer_item_code IS NOT NULL OR customer_description IS NOT NULL)
);
CREATE UNIQUE INDEX IF NOT EXISTS customer_product_aliases_uidx
    ON public.customer_product_aliases (customer_id, alias_key);
CREATE INDEX IF NOT EXISTS idx_customer_product_aliases_desc
    ON public.customer_product_aliases
       (customer_id, lower(regexp_replace(btrim(customer_description), '\s+', ' ', 'g')))
    WHERE customer_description IS NOT NULL;

ALTER TABLE public.sales_orders
    ADD COLUMN IF NOT EXISTS customer_po text,
    ADD COLUMN IF NOT EXISTS source_document_id integer
        REFERENCES public.purchase_documents(id);
-- Dedupe lookup (warn-only, no unique constraint — mirrors the ER dedupe).
CREATE INDEX IF NOT EXISTS idx_sales_orders_customer_po
    ON public.sales_orders (customer_id,
        lower(regexp_replace(btrim(customer_po), '\s+', ' ', 'g')))
    WHERE customer_po IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_sales_orders_source_doc
    ON public.sales_orders (source_document_id)
    WHERE source_document_id IS NOT NULL;

COMMIT;
