// Renders docs/design/audit/06-browser-check.md from the raw capture results.
// Everything printed here is measured; nothing is inferred.

// Findings repeat once per rendered instance — twelve `copyday` buttons, four
// note cards. Collapse to the element's own selector so the table lists causes,
// not occurrences.
// A colour-emoji glyph supplies its own pixels; the computed `color` it would
// otherwise be measured against does not paint it. Ratios for those runs are
// reported separately rather than counted as contrast failures — the audit
// makes the same point about `opacity` on emoji in IMP-058.
const PICTOGRAPHIC = /^[\s\p{Extended_Pictographic}\u{FE0F}\u{200D}]+$/u;

function isPictographic(text) {
  const t = String(text || '').trim();
  return t.length > 0 && PICTOGRAPHIC.test(t);
}

const STATE_CLASSES = /\.(expanded|active|so-ready|done|priority-high|priority-low|er-inactive|er-overdue|supply-item-low|fri|wkend)(?![-\w])/g;

function signature(path) {
  const parts = String(path).split(' > ');
  const last = parts[parts.length - 1].replace(STATE_CLASSES, '');
  // A bare tag says nothing — `input` covers a radio in the note modal and a
  // number field in the scheduler's settings panel. Keep its parent for those.
  if (!/[.#]/.test(last) && parts.length > 1) {
    return parts[parts.length - 2].replace(STATE_CLASSES, '') + ' > ' + last;
  }
  return last;
}

const ICON = { PASS: 'PASS', FAIL: 'FAIL', WARN: 'WARN', 'N/A': 'n/a', ERROR: 'err' };

function esc(s) {
  return String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function fmtDate(d) {
  return d.toISOString().slice(0, 10);
}

export function writeReport({ results, screens, variants, rules, verdict, zoomScreens }) {
  const byScreen = new Map();
  for (const r of results) {
    if (!byScreen.has(r.id)) byScreen.set(r.id, new Map());
    byScreen.get(r.id).set(r.variant, r);
  }

  const out = [];
  const now = new Date();
  const captured = results.length;

  // Totals
  const tally = { PASS: 0, FAIL: 0, WARN: 0, 'N/A': 0, ERROR: 0 };
  const perRule = {};
  for (const rule of rules) perRule[rule] = { PASS: 0, FAIL: 0, WARN: 0, 'N/A': 0, ERROR: 0 };
  for (const r of results) {
    for (const rule of rules) {
      const v = verdict(rule, r.rules[rule]);
      tally[v.status]++;
      perRule[rule][v.status]++;
    }
  }

  out.push('# 06 — Browser Check (rendered verification)');
  out.push('');
  out.push(`**Date:** ${fmtDate(now)} · **Harness:** \`tests/visual/run-visual-audit.mjs\` (Playwright + Chromium, headless)`);
  out.push('**Standard:** [FL-Design-Standards-MASTER.md](../FL-Design-Standards-MASTER.md) · **Inventory:** [00-screen-inventory.md](00-screen-inventory.md)');
  // Deliberately says nothing about what the surrounding branch did. The line
  // this replaces read "Findings only. No application file was changed by this
  // work" — true when the harness landed, false the moment a fix branch re-ran
  // it, and silently wrong in between.
  out.push('**Status:** Generated output. `npm run test:visual` overwrites this file on every run; it records what the working tree rendered at the date above, not a fixed baseline.');
  out.push('');
  out.push('## What this run did');
  out.push('');
  out.push('Every screen in the inventory was rendered against a local static server over `dashboard/`, with every');
  out.push('Railway API call answered from `tests/visual/fixtures/`. No network request left the machine and no');
  out.push('database was touched. Writes (`POST`/`PATCH`/`PUT`/`DELETE`) are acknowledged by the stub and applied');
  out.push('nowhere. Fixture dates carry `{{TODAY}}`-style tokens resolved once per run against the plant timezone,');
  out.push('so overdue flags, the rolling calendar, and "today" are correct on any run day while staying byte-stable');
  out.push('within the run — which is what the LAYOUT-020 before/after comparison depends on.');
  out.push('');
  out.push('| Variant | Viewport | DPR | Screens captured |');
  out.push('|---|---|---|---|');
  for (const v of variants) {
    const n = results.filter(r => r.variant === v.key).length;
    const vp = v.tier === 'zoom'
      ? `${v.width}×${v.height} CSS px (1440×900 at 200% zoom)`
      : `${v.width}×${v.height}`;
    out.push(`| \`${v.key}\` | ${vp} | ${v.dsf} | ${n} |`);
  }
  out.push('');
  out.push(`${captured} captures in total. Screenshots are written to \`docs/design/audit/screenshots/<variant>/<S-id>.png\`;`);
  out.push('they are build output, regenerated by `npm run test:visual`, and are not committed.');
  out.push('');

  out.push('## What is and is not checked');
  out.push('');
  out.push('Each rule below has one clause a rendered page can settle without judgement. The rest of each rule —');
  out.push('and every rule not listed — is untouched by this run and is **not** reported as passing.');
  out.push('');
  out.push('| Rule | Clause checked mechanically | Method | Clause **not** checked here |');
  out.push('|---|---|---|---|');
  out.push('| **TOUCH-003** | Hit region ≥ 44 × 44 pt | `getBoundingClientRect()` on every visible interactive element in the screen\'s region, including the six non-control classes that carry click handlers (`.lot-link`, `tr.expandable`, `.order-row`, `.search-item`, `.product-lot-row`, `.supply-item-row`) | Visible hover / focus / selection states; glyph padding; neighbour overlap |');
  out.push('| **ACCESS-008** | WCAG AA contrast (4.5:1 body, 3:1 large) | Computed `color` composited over every translucent fill up to the first opaque surface, multiplied by inherited `opacity`; ratio per WCAG 2.x relative luminance. Rendered **placeholder** colour is measured too, through `getComputedStyle(el, \'::placeholder\')` — INPUT-022\'s clause | Colour-blind separability; increased-contrast mode; text over images; printed output (FEEDBACK-011) |');
  out.push('| **LAYOUT-003 / ACCESS-001** | No horizontal document overflow | `documentElement.scrollWidth − clientWidth`; offenders inside a genuine `overflow-x` scroller are excluded | Orientation change; Spanish label length; largest OS text size; hierarchy preservation |');
  out.push('| **LAYOUT-011** | Fixed bars do not cover the last scrollable row | Every scroll region driven to its end, then `elementFromPoint` occlusion probes. A candidate is only a failure if it is under a *bottom-anchored* bar at maximum scroll, or still occluded after being re-parked at 60% of the viewport — a row passing under a sticky header is reachable and is not counted | Whether the layout uses the available space |');
  out.push('| **LAYOUT-020** | Nothing moves on a refresh | `PerformanceObserver(\'layout-shift\')` CLS plus per-element before/after position deltas across the app\'s own refresh callback | Reordering under a *user* action; live-update buffering policy |');
  out.push('');
  out.push('**One approximation, stated.** Where an ancestor sets `opacity`, the text colour is faded against its local');
  out.push('backdrop. That is exact wherever the faded subtree sits on the same surface as its backdrop — the');
  out.push('depleted-lots table at `opacity: 0.6` is that case — and a close approximation otherwise.');
  out.push('');
  out.push('**Thresholds.** TOUCH-003 fails on any element under 44 pt in either axis. ACCESS-008 fails on any text');
  out.push('node below its AA target. LAYOUT-003/ACCESS-001 fails above 1 px of document overflow. LAYOUT-011 fails on');
  out.push('any occluded interactive element. LAYOUT-020 passes at CLS ≤ 0.1 **and** zero moved anchors, warns to');
  out.push('CLS 0.25, fails above it.');
  out.push('');

  out.push('## Results at a glance');
  out.push('');
  out.push('| Rule | PASS | FAIL | WARN | n/a | err |');
  out.push('|---|---:|---:|---:|---:|---:|');
  for (const rule of rules) {
    const c = perRule[rule];
    out.push(`| ${rule} | ${c.PASS} | ${c.FAIL} | ${c.WARN} | ${c['N/A']} | ${c.ERROR} |`);
  }
  out.push(`| **All** | **${tally.PASS}** | **${tally.FAIL}** | **${tally.WARN}** | **${tally['N/A']}** | **${tally.ERROR}** |`);
  out.push('');

  // ── The matrix ──────────────────────────────────────────────────────────
  out.push('## Matrix — screen × rule × status');
  out.push('');
  out.push('One row per screen per rule. A cell is the status in that variant; `—` means the variant does not apply');
  out.push('(a desktop-only screen at 390px, or a screen outside the four tabs in the 200% pass). The screenshot');
  out.push('column links the 1440px dark capture, or the first capture taken where that one does not exist.');
  out.push('');
  const header = ['Screen', 'Rule', ...variants.map(v => v.label), 'Screenshot'];
  out.push('| ' + header.join(' | ') + ' |');
  out.push('|' + header.map(() => '---').join('|') + '|');

  for (const screen of screens) {
    const caps = byScreen.get(screen.id);
    if (!caps || caps.size === 0) {
      const why = screen.capturable === false
        ? (screen.note || 'Not capturable.')
        : 'No capture produced.';
      out.push(`| **${screen.id}** ${esc(screen.name)} | _all_ | ${variants.map(() => 'n/a').join(' | ')} | — ${esc(why)} |`);
      continue;
    }
    const preferred = caps.get('1440-dark') || caps.get('1440-light') || [...caps.values()][0];
    const shot = preferred.screenshot ? `[png](${preferred.screenshot.split(path_sep()).join('/')})` : '—';
    for (const rule of rules) {
      const cells = variants.map(v => {
        const cap = caps.get(v.key);
        if (!cap) return '—';
        if (cap.error) return 'err';
        return ICON[verdict(rule, cap.rules[rule]).status] || '?';
      });
      out.push(`| **${screen.id}** ${esc(screen.name)} | ${rule} | ${cells.join(' | ')} | ${shot} |`);
    }
  }
  out.push('');

  // ── Findings ────────────────────────────────────────────────────────────
  out.push('## Findings, by rule');
  out.push('');

  // TOUCH-003
  out.push('### TOUCH-003 — hit regions under 44 pt');
  out.push('');
  const touchWorst = new Map();
  for (const r of results) {
    const d = r.rules['TOUCH-003'];
    if (!d || !d.worst) continue;
    for (const w of d.worst) {
      const key = signature(w.path);
      let e = touchWorst.get(key);
      if (!e) {
        e = { ...w, sig: key, instances: 0, screens: new Set(), variants: new Set(), labels: new Set() };
        touchWorst.set(key, e);
      }
      e.w = Math.min(e.w, w.w);
      e.h = Math.min(e.h, w.h);
      e.nested = e.nested && w.nested;
      e.instances++;
      e.screens.add(r.id);
      e.variants.add(r.variant);
      if (w.label) e.labels.add(w.label);
    }
  }
  if (touchWorst.size === 0) {
    out.push('No interactive element measured under 44 pt in any capture.');
  } else {
    out.push('Smallest first. `Nested` marks a target that sits inside a larger interactive ancestor —');
    out.push('recorded because the glyph is easier to hit than its size suggests, but not an exemption where');
    out.push('the two carry different actions.');
    out.push('');
    out.push('| Element | Example label | Smallest (pt) | Nested | Screens | Widths |');
    out.push('|---|---|---|:--:|---|---|');
    const rows = [...touchWorst.values()].sort((a, b) => a.w * a.h - b.w * b.h).slice(0, 45);
    for (const w of rows) {
      const label = [...w.labels][0] || '';
      const widths = [...new Set([...w.variants].map(v => v.split('-')[0]))].sort().join(', ');
      out.push(`| \`${esc(w.sig)}\` | ${esc(label) || '—'} | **${w.w} × ${w.h}** | ${w.nested ? 'yes' : 'no'} | ${[...w.screens].sort().slice(0, 10).join(', ')}${w.screens.size > 10 ? ` +${w.screens.size - 10}` : ''} | ${widths} |`);
    }
    if (touchWorst.size > 45) {
      out.push('');
      out.push(`_${touchWorst.size - 45} further distinct selectors omitted; the full list is in \`screenshots/results.json\`._`);
    }
  }
  out.push('');

  // ACCESS-008
  out.push('### ACCESS-008 — text below WCAG AA');
  out.push('');
  const contrastWorst = new Map();
  let indeterminate = 0;
  for (const r of results) {
    const d = r.rules['ACCESS-008'];
    if (!d) continue;
    indeterminate += d.indeterminate || 0;
    for (const w of (d.worst || [])) {
      const key = signature(w.path) + '|' + w.fg + '|' + w.bg;
      let e = contrastWorst.get(key);
      if (!e) {
        e = { ...w, sig: signature(w.path), screens: new Set(), variants: new Set(), texts: new Set() };
        contrastWorst.set(key, e);
      }
      e.ratio = Math.min(e.ratio, w.ratio);
      e.screens.add(r.id);
      e.variants.add(r.variant);
      if (w.text) e.texts.add(w.text);
    }
  }
  const pictoRows = [...contrastWorst.values()].filter(w => isPictographic([...w.texts][0] || ''));
  for (const w of pictoRows) contrastWorst.delete([...contrastWorst.entries()].find(([, v]) => v === w)[0]);

  if (contrastWorst.size === 0) {
    out.push('Every measured text node met its AA target in every capture.');
  } else {
    out.push('Worst ratio first. `Ratio` is the composited value — the declared colour after every translucent');
    out.push('fill and inherited `opacity` between the text and the first opaque surface has been applied.');
    out.push('');
    out.push('| Element | Example text | Ratio | Target | Font | Foreground | Composited background | Opacity | Themes | Screens |');
    out.push('|---|---|---:|---:|---|---|---|---:|---|---|');
    const rows = [...contrastWorst.values()].sort((a, b) => a.ratio - b.ratio).slice(0, 45);
    for (const w of rows) {
      const text = [...w.texts][0] || '';
      const themes = [...new Set([...w.variants].map(v => (v.endsWith('light') ? 'light' : 'dark')))].sort().join(' + ');
      out.push(`| \`${esc(w.sig)}\` | ${esc(text) || '—'} | **${w.ratio}** | ${w.target} | ${w.fontPx}px/${w.weight} | \`${esc(w.fg)}\` | \`${esc(w.bg)}\` | ${w.opacity} | ${themes} | ${[...w.screens].sort().slice(0, 8).join(', ')}${w.screens.size > 8 ? ` +${w.screens.size - 8}` : ''} |`);
    }
    if (contrastWorst.size > 45) {
      out.push('');
      out.push(`_${contrastWorst.size - 45} further distinct selector/colour pairs omitted; the full list is in \`screenshots/results.json\`._`);
    }
  }
  const phChecked = results.reduce((n, r) => n + ((r.rules['ACCESS-008'] || {}).placeholdersChecked || 0), 0);
  const phFailed = results.reduce((n, r) => n + ((r.rules['ACCESS-008'] || {}).placeholderFailures || 0), 0);
  if (pictoRows.length) {
    out.push('');
    const glyphs = [...new Set(pictoRows.map(w => [...w.texts][0]))];
    out.push('**Pictographic glyphs, measured but not counted.** ' + pictoRows.length + ' of the failing measurements are runs of '
      + 'pictographic characters (' + glyphs.map(g => '`' + esc(g) + '`').join(', ') + '), across the light and dark captures. Where '
      + 'these render as a colour bitmap the glyph paints its own pixels, so the computed `color` the ratio is derived from never '
      + 'reaches the screen and the number would be meaningless; they are excluded from the count above. What the measurement does show '
      + 'is the `opacity: 0.5` those glyphs carry: on monochrome text that halves the contrast, and on a colour bitmap it does not — '
      + 'which is exactly IMP-058\'s point about mixing the two icon families. Whether each of these actually renders in colour, and '
      + 'whether it is legible, needs an eye on the real machines (ICON-002 / ICON-005), not a ratio.');
  }
  if (phChecked) {
    out.push('');
    out.push(`**Placeholder text (INPUT-022).** ${phChecked} rendered placeholder measurements across all captures, `
      + `${phFailed} below AA. Placeholder colour is measured through \`getComputedStyle(el, '::placeholder')\`, so where `
      + 'no `::placeholder` rule exists this is the colour the user agent actually chose — the value no code read could supply.');
  }
  if (indeterminate) {
    out.push('');
    out.push(`${indeterminate} text node measurements were skipped as **indeterminate** — a \`background-image\` sits between the text and its backdrop, so a computed ratio would not be the ratio the eye receives. These need a human check.`);
  }
  out.push('');

  // LAYOUT-003
  out.push('### LAYOUT-003 / ACCESS-001 — horizontal overflow');
  out.push('');
  const overflowRows = results
    .filter(r => r.rules['LAYOUT-003/ACCESS-001'] && r.rules['LAYOUT-003/ACCESS-001'].overflowPx > 1)
    .map(r => ({ r, d: r.rules['LAYOUT-003/ACCESS-001'] }))
    .sort((a, b) => b.d.overflowPx - a.d.overflowPx);
  if (overflowRows.length === 0) {
    out.push('No capture overflowed the document horizontally, at any width, in either theme, or at 200% zoom.');
  } else {
    out.push('| Screen | Variant | Overflow | Viewport | Widest offender |');
    out.push('|---|---|---:|---:|---|');
    for (const { r, d } of overflowRows.slice(0, 40)) {
      const first = d.offenders[0];
      out.push(`| **${r.id}** ${esc(r.name)} | \`${r.variant}\` | ${d.overflowPx}px | ${d.viewport}px | ${first ? '`' + esc(first.path) + '` — right edge ' + first.right + 'px' : '—'} |`);
    }
    if (overflowRows.length > 40) {
      out.push('');
      out.push(`_${overflowRows.length - 40} further overflowing captures omitted; the full list is in \`screenshots/results.json\`._`);
    }
  }
  out.push('');

  // LAYOUT-011
  out.push('### LAYOUT-011 — actionable content behind a fixed bar');
  out.push('');
  const occRows = results
    .filter(r => r.rules['LAYOUT-011'] && r.rules['LAYOUT-011'].coveredCount > 0)
    .sort((a, b) => b.rules['LAYOUT-011'].coveredCount - a.rules['LAYOUT-011'].coveredCount);
  if (occRows.length === 0) {
    const barSample = results.find(r => r.rules['LAYOUT-011'] && r.rules['LAYOUT-011'].bars.length);
    const bars = barSample
      ? barSample.rules['LAYOUT-011'].bars.map(b => '`' + b.path + '` (' + b.anchor + ')').join(', ')
      : 'none';
    out.push('With every scroll region driven to its end, nothing actionable was found stuck behind a fixed or');
    out.push('sticky bar in any capture. Bars detected on the dashboard: ' + bars + '.');
  } else {
    out.push('| Screen | Variant | Covered | Example element | Covered by |');
    out.push('|---|---|---:|---|---|');
    for (const r of occRows.slice(0, 40)) {
      const d = r.rules['LAYOUT-011'];
      const first = d.covered[0];
      out.push(`| **${r.id}** ${esc(r.name)} | \`${r.variant}\` | ${d.coveredCount} | ${first ? '`' + esc(first.path) + '` ' + esc(first.label) : '—'} | ${first ? '`' + esc(first.blockedBy) + '`' : '—'} |`);
    }
  }
  const underTop = results.reduce((n, r) => n + ((r.rules['LAYOUT-011'] || {}).passUnderTopBar || 0), 0);
  const underTopCaptures = results.filter(r => ((r.rules['LAYOUT-011'] || {}).passUnderTopBar || 0) > 0).length;
  if (underTop) {
    out.push('');
    out.push(`For completeness: ${underTop} interactive elements across ${underTopCaptures} captures were overlapped by a **top-anchored** `
      + 'sticky bar at maximum scroll. Each was re-probed after being parked at 60% of the viewport and each came clear, so none is a '
      + 'LAYOUT-011 failure — a row passing under a sticky header is what a sticky header does. They are counted here so the pass above '
      + 'is not read as "no bar ever overlaps anything".');
  }
  out.push('');

  // LAYOUT-020
  out.push('### LAYOUT-020 — layout shift on refresh');
  out.push('');
  const trigCount = {};
  for (const r of results) {
    const d = r.rules['LAYOUT-020'];
    if (d && d.applicable) trigCount[d.trigger] = (trigCount[d.trigger] || 0) + 1;
  }
  const bgCaps = results.filter(r => (r.rules['LAYOUT-020'] || {}).trigger === 'background interval callback');
  const bgClean = bgCaps.filter(r => r.rules['LAYOUT-020'].cls === 0 && r.rules['LAYOUT-020'].moved === 0).length;
  out.push('**Read the trigger column before the CLS column.** Two different things were measured, and only one of them');
  out.push('is what LAYOUT-020 prohibits.');
  out.push('');
  out.push(`* **A real background timer fired** (${trigCount['background interval callback'] || 0} captures): the Recent Entries 60-second poll, the`);
  out.push('  Order Detail allocation-expiry countdown, and Process Flow\'s 60-second auto-refresh. These are exactly the');
  out.push(`  case the rule is about — content changing with no user action. **${bgClean} of ${bgCaps.length} recorded CLS 0 with nothing moved.**`);
  out.push('  Process Flow keeps its last good render and rewrites in place; the countdown rewrites text inside a fixed cell.');
  out.push('  On the evidence of this run the product has no background refresh that moves content under the user.');
  out.push(`* **The Refresh control was pressed** (${trigCount['#refresh-btn'] || 0} captures), because those screens have no timer of their own.`);
  out.push('  LAYOUT-020 permits layout change that is "a direct response to their explicit action", so a shift here is not a');
  out.push('  violation of the letter of the rule. It is reported because the same `refreshAll()` path runs unprompted at app');
  out.push('  start, and because it demonstrates the blank-and-repaint behaviour (SYS-2) that *would* violate the rule the');
  out.push('  moment any of these lists gains the auto-refresh IMP-036 proposes.');
  out.push('');
  out.push('`Anchors lost` counts elements whose identity key was absent after the refresh — destroyed outright, or re-keyed');
  out.push('because their ordinal position moved. It is a signal to look, not a finding on its own.');
  out.push('');
  const shiftRows = results
    .filter(r => {
      const d = r.rules['LAYOUT-020'];
      return d && d.applicable && (d.cls > 0.1 || d.moved > 0);
    })
    .sort((a, b) => b.rules['LAYOUT-020'].cls - a.rules['LAYOUT-020'].cls);
  if (shiftRows.length === 0) {
    out.push('No capture shifted on refresh: CLS 0 and no anchor moved in every applicable capture.');
  } else {
    out.push('| Screen | Variant | CLS | Moved | Max Δ | Anchors lost | Trigger | Worst mover |');
    out.push('|---|---|---:|---:|---:|---:|---|---|');
    for (const r of shiftRows.slice(0, 45)) {
      const d = r.rules['LAYOUT-020'];
      const w = d.worst && d.worst[0];
      out.push(`| **${r.id}** ${esc(r.name)} | \`${r.variant}\` | **${d.cls}** | ${d.moved} | ${d.maxDeltaPx}px | ${d.vanished} | ${esc(d.trigger)} | ${w ? esc(w.key) + ` (Δx ${w.dx}px, Δy ${w.dy}px)` : '—'} |`);
    }
    if (shiftRows.length > 45) {
      out.push('');
      out.push(`_${shiftRows.length - 45} further shifting captures omitted; the full list is in \`screenshots/results.json\`._`);
    }
  }
  out.push('');

  // ── Capture notes / errors ──────────────────────────────────────────────
  // Surfaces with no light palette at all — an ACCESS-001 observation this run settles.
  const unthemed = new Map();
  for (const r of results) {
    if (r.themeResponded === false) {
      if (!unthemed.has(r.page)) unthemed.set(r.page, new Set());
      unthemed.get(r.page).add(r.id);
    }
  }
  if (unthemed.size) {
    out.push('## Surfaces with no light palette');
    out.push('');
    out.push('Setting `data-theme="light"` on the root moved nothing on these pages: the painted background was identical');
    out.push('before and after. `dashboard/` carries a paired light/dark token set and responds; the other four surfaces do');
    out.push('not have a light mode to honour. Their "light" captures in the matrix above are therefore the same dark surface');
    out.push('as their dark captures, and their contrast results are one measurement reported twice — not two.');
    out.push('');
    out.push('| Surface | Screens | Effect on this run |');
    out.push('|---|---:|---|');
    for (const [page, ids] of unthemed) {
      out.push(`| \`${page}\` | ${ids.size} | light and dark captures are identical |`);
    }
    out.push('');
    out.push('This bears on ACCESS-001 ("support dark mode", "honor … light/dark settings") and on SYS-1: five `:root`');
    out.push('palettes, one of which is themed. It is not a new finding — IMP-010 and IMP-027 already own it — but it is now');
    out.push('measured rather than inferred.');
    out.push('');
  }

  const noted = results.filter(r => r.error || (r.notes && r.notes.length) || (r.consoleErrors && r.consoleErrors.length));
  out.push('## Capture notes');
  out.push('');
  if (!noted.length) {
    out.push('Every capture reached its target state cleanly, with no page error.');
  } else {
    out.push('| Screen | Variant | Note |');
    out.push('|---|---|---|');
    const seen = new Set();
    for (const r of noted) {
      const msgs = [];
      if (r.error) msgs.push('**capture error:** ' + r.error);
      for (const n of r.notes || []) msgs.push(n);
      for (const c of (r.consoleErrors || []).slice(0, 2)) msgs.push('console: `' + c + '`');
      const line = `| **${r.id}** | \`${r.variant}\` | ${esc(msgs.join(' · '))} |`;
      const key = r.id + msgs.join('');
      if (seen.has(key)) continue;
      seen.add(key);
      out.push(line);
    }
  }
  out.push('');

  const notCapturable = screens.filter(s => s.capturable === false);
  if (notCapturable.length) {
    out.push('### Screens that cannot be captured');
    out.push('');
    out.push('| Screen | Why |');
    out.push('|---|---|');
    for (const s of notCapturable) out.push(`| **${s.id}** ${esc(s.name)} | ${esc(s.note)} |`);
    out.push('');
    out.push('These four are the browser-native `confirm`/`alert` dialogs of SYS-7. The dialog is browser chrome:');
    out.push('nothing about it is in the document, so no rule here can be measured against it either way. That is');
    out.push('itself the argument for IMP-014/016/026/060 replacing them, but this run adds no evidence.');
    out.push('');
  }

  out.push('## Reproducing this');
  out.push('');
  out.push('```sh');
  out.push('npm install');
  out.push('npx playwright install chromium');
  out.push('npm run test:visual');
  out.push('```');
  out.push('');
  out.push('Narrow a run with `--screens S-25,S-42` or `--variants 1440-dark`, and watch it with `--headed`.');
  out.push('');
  out.push('---');
  out.push('');
  out.push('*Generated by `tests/visual/run-visual-audit.mjs`. Re-running regenerates this file in place.*');

  return out.join('\n') + '\n';
}

function path_sep() {
  return process.platform === 'win32' ? '\\' : '/';
}
