// Renders docs/design/audit/06-browser-check.md from the raw capture results.
// Everything printed here is measured; nothing is inferred.

// Findings repeat once per rendered instance — twelve `copyday` buttons, four
// note cards. Collapse to the element's own selector so the table lists causes,
// not occurrences.
// A colour-emoji glyph supplies its own pixels; the computed `color` it would
// otherwise be measured against does not paint it. Ratios for those runs are
// reported separately rather than counted as contrast failures — the audit
// makes the same point about `opacity` on emoji in IMP-058.
const PICTOGRAPHIC = /^[\s\p{Extended_Pictographic}\u{FE0F}\u{200D}]+$/u;

function isPictographic(text) {
  const t = String(text || '').trim();
  return t.length > 0 && PICTOGRAPHIC.test(t);
}

const STATE_CLASSES = /\.(expanded|active|so-ready|done|priority-high|priority-low|er-inactive|er-overdue|supply-item-low|fri|wkend)(?![-\w])/g;

function signature(path) {
  const parts = String(path).split(' > ');
  const last = parts[parts.length - 1].replace(STATE_CLASSES, '');
  // A bare tag says nothing — `input` covers a radio in the note modal and a
  // number field in the scheduler's settings panel. Keep its parent for those.
  if (!/[.#]/.test(last) && parts.length > 1) {
    return parts[parts.length - 2].replace(STATE_CLASSES, '') + ' > ' + last;
  }
  return last;
}

const ICON = { PASS: 'PASS', FAIL: 'FAIL', WARN: 'WARN', 'N/A': 'n/a', ERROR: 'err' };

function esc(s) {
  return String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function fmtDate(d) {
  return d.toISOString().slice(0, 10);
}

export function writeReport({ results, screens, variants, rules, verdict, zoomScreens }) {
  const byScreen = new Map();
  for (const r of results) {
    if (!byScreen.has(r.id)) byScreen.set(r.id, new Map());
    byScreen.get(r.id).set(r.variant, r);
  }

  const out = [];
  const now = new Date();
  const captured = results.length;

  // Totals
  const tally = { PASS: 0, FAIL: 0, WARN: 0, 'N/A': 0, ERROR: 0 };
  const perRule = {};
  for (const rule of rules) perRule[rule] = { PASS: 0, FAIL: 0, WARN: 0, 'N/A': 0, ERROR: 0 };
  for (const r of results) {
    for (const rule of rules) {
      const v = verdict(rule, r.rules[rule]);
      tally[v.status]++;
      perRule[rule][v.status]++;
    }
  }

  out.push('# 06 — Browser Check (rendered verification)');
  out.push('');
  out.push(`**Date:** ${fmtDate(now)} · **Harness:** \`tests/visual/run-visual-audit.mjs\` (Playwright + Chromium, headless)`);
  out.push('**Standard:** [FL-Design-Standards-MASTER.md](../FL-Design-Standards-MASTER.md) · **Inventory:** [00-screen-inventory.md](00-screen-inventory.md)');
  // Deliberately says nothing about what the surrounding branch did. The line
  // this replaces read "Findings only. No application file was changed by this
  // work" — true when the harness landed, false the moment a fix branch re-ran
  // it, and silently wrong in between.
  out.push('**Status:** Generated output. `npm run test:visual` overwrites this file on every run; it records what the working tree rendered at the date above, not a fixed baseline.');
  out.push('');
  out.push('## What this run did');
  out.push('');
  out.push('Every screen in the inventory was rendered against a local static server over `dashboard/`, with every');
  out.push('Railway API call answered from `tests/visual/fixtures/`. No network request left the machine and no');
  out.push('database was touched. Writes (`POST`/`PATCH`/`PUT`/`DELETE`) are acknowledged by the stub and applied');
  out.push('nowhere. Fixture dates carry `{{TODAY}}`-style tokens resolved once per run against the plant timezone,');
  out.push('so overdue flags, the rolling calendar, and "today" are correct on any run day while staying byte-stable');
  out.push('within the run — which is what the LAYOUT-020 before/after comparison depends on.');
  out.push('');
  out.push('| Variant | Viewport | DPR | Screens captured |');
  out.push('|---|---|---|---|');
  for (const v of variants) {
    const n = results.filter(r => r.variant === v.key).length;
    const vp = v.tier === 'zoom'
      ? `${v.width}×${v.height} CSS px (1440×900 at 200% zoom)`
      : `${v.width}×${v.height}`;
    out.push(`| \`${v.key}\` | ${vp} | ${v.dsf} | ${n} |`);
  }
  out.push('');
  out.push(`${captured} captures in total. Screenshots are written to \`docs/design/audit/screenshots/<variant>/<S-id>.png\`;`);
  out.push('they are build output, regenerated by `npm run test:visual`, and are not committed.');
  out.push('');

  out.push('## What is and is not checked');
  out.push('');
  out.push('Each rule below has one clause a rendered page can settle without judgement. The rest of each rule —');
  out.push('and every rule not listed — is untouched by this run and is **not** reported as passing.');
  out.push('');
  out.push('| Rule | Clause checked mechanically | Method | Clause **not** checked here |');
  out.push('|---|---|---|---|');
  out.push('| **TOUCH-003** | Hit region ≥ 44 × 44 pt | `getBoundingClientRect()` on every visible interactive element in the screen\'s region, including the six non-control classes that carry click handlers (`.lot-link`, `tr.expandable`, `.order-row`, `.search-item`, `.product-lot-row`, `.supply-item-row`) | Visible hover / focus / selection states; glyph padding; neighbour overlap |');
  out.push('| **ACCESS-008** | WCAG AA contrast (4.5:1 body, 3:1 large) | Computed `color` composited over every translucent fill up to the first opaque surface, multiplied by inherited `opacity`; ratio per WCAG 2.x relative luminance. Rendered **placeholder** colour is measured too, through `getComputedStyle(el, \'::placeholder\')` — INPUT-022\'s clause | Colour-blind separability; increased-contrast mode; text over images; printed output (FEEDBACK-011) |');
  out.push('| **LAYOUT-003 / ACCESS-001** | No horizontal document overflow | `documentElement.scrollWidth − clientWidth`; offenders inside a genuine `overflow-x` scroller are excluded | Orientation change; Spanish label length; largest OS text size; hierarchy preservation |');
  out.push('| **LAYOUT-011** | Fixed bars do not cover the last scrollable row | Every scroll region driven to its end, then `elementFromPoint` occlusion probes. A candidate is only a failure if it is under a *bottom-anchored* bar at maximum scroll, or still occluded after being re-parked at 60% of the viewport — a row passing under a sticky header is reachable and is not counted | Whether the layout uses the available space |');
  out.push('| **LAYOUT-020** | Nothing moves on a refresh | `PerformanceObserver(\'layout-shift\')` CLS plus per-element before/after position deltas across the app\'s own refresh callback | Reordering under a *user* action; live-update buffering policy |');
  out.push('| **STATUS-002** | No coloured badge announces a nominal value | Every chip-shaped element\'s rendered text matched against the rule\'s nominal-phrase list, then tested for a saturated fill, border or text colour | Whether the *absence* of a chip reads as "normal" to an operator |');
  out.push('| **STATUS-004** | At most one danger/warning-toned element per list row | Tone decided by hue against the resolved `--danger` / `--warning` tokens (±12°, saturation ≥ 0.22), counted per row. Inherited `color` counts once, on the element that introduces it | Whether the surviving alarm is the *most severe* of the conditions present |');
  out.push('| **STATUS-005** | The explanation hook exists | `data-explain` naming a real element, `aria-describedby` naming the same id, and a focus stop, on every chip. Chips whose only explanation is `title=` are counted separately | The explanation\'s **content** — definition plus this record\'s quantities, lines and dates. Manual |');
  out.push('| **STATUS-006** | One number format | Rendered numeric text: ≥ 3 decimal places, ≥ 1,000 without a separator, decimal pounds, pallets past one decimal, and digits in an aligned column without tabular figures. Codes, dates, bare years and any column whose header names an identifier (SKU, Code, Lot, Order) are skipped; the tabular clause is measured only where digit width can misalign a column — a separator, a decimal, a unit, or three or more digits | Whether the same quantity agrees between screen, print and export |');
  out.push('| **STATUS-007** | No orphan placeholders | Elements whose entire text is a dash, `n/a`, `none`, `null` or `undefined`, outside a table cell (a cell dash holds column alignment and is the rule\'s exception) | Whether omitting the line loses a distinction the reader needed |');
  out.push('| **STATUS-008** | List rows ≤ 56 px | Measured row height at viewports ≥ 1200 px. Rows the user expanded are excluded by class | Whether what was pushed off the row is reachable in one step |');
  out.push('| **STATUS-010** | No developer vocabulary | Denylist scan over rendered text and over `title` / `placeholder` / `aria-label`, plus any `snake_case` identifier. "returns" is not on the list: on a factory floor it means returned goods | Tone, jargon that is not on the list, Spanish copy |');
  out.push('| **STATUS-011** | A disclaimer appears once | Sentences of 40 characters or more, counted within one capture; any rendered twice is reported | Whether the one surviving copy sits at first relevance |');
  out.push('');
  out.push('**One approximation, stated.** Where an ancestor sets `opacity`, the text colour is faded against its local');
  out.push('backdrop. That is exact wherever the faded subtree sits on the same surface as its backdrop — the');
  out.push('depleted-lots table at `opacity: 0.6` is that case — and a close approximation otherwise.');
  out.push('');
  out.push('**Thresholds.** TOUCH-003 fails on any element under 44 pt in either axis. ACCESS-008 fails on any text');
  out.push('node below its AA target. LAYOUT-003/ACCESS-001 fails above 1 px of document overflow. LAYOUT-011 fails on');
  out.push('any occluded interactive element. LAYOUT-020 passes at CLS ≤ 0.1 **and** zero moved anchors, warns to');
  out.push('CLS 0.25, fails above it.');
  out.push('The STATUS rules fail on any single instance: one coloured nominal badge, one row with two alarms, one');
  out.push('chip without the hook, one mis-formatted number, one orphan dash, one row over 56 px, one denylisted term,');
  out.push('one repeated sentence.');
  out.push('');
  out.push('**STATUS-005 checks the MASTER-defined `data-explain` hook.** The Sales Orders list implements it;');
  out.push('screens that have not yet adopted the hook still report failures, including chips that currently rely');
  out.push('only on a `title` tooltip that a touch device never shows.');
  out.push('');

  out.push('## Results at a glance');
  out.push('');
  out.push('| Rule | PASS | FAIL | WARN | n/a | err |');
  out.push('|---|---:|---:|---:|---:|---:|');
  for (const rule of rules) {
    const c = perRule[rule];
    out.push(`| ${rule} | ${c.PASS} | ${c.FAIL} | ${c.WARN} | ${c['N/A']} | ${c.ERROR} |`);
  }
  out.push(`| **All** | **${tally.PASS}** | **${tally.FAIL}** | **${tally.WARN}** | **${tally['N/A']}** | **${tally.ERROR}** |`);
  out.push('');

  // ── The matrix ──────────────────────────────────────────────────────────
  out.push('## Matrix — screen × rule × status');
  out.push('');
  out.push('One row per screen per rule. A cell is the status in that variant; `—` means the variant does not apply');
  out.push('(a desktop-only screen at 390px, or a screen outside the four tabs in the 200% pass). The screenshot');
  out.push('column links the 1440px dark capture, or the first capture taken where that one does not exist.');
  out.push('');
  const header = ['Screen', 'Rule', ...variants.map(v => v.label), 'Screenshot'];
  out.push('| ' + header.join(' | ') + ' |');
  out.push('|' + header.map(() => '---').join('|') + '|');

  for (const screen of screens) {
    const caps = byScreen.get(screen.id);
    if (!caps || caps.size === 0) {
      const why = screen.capturable === false
        ? (screen.note || 'Not capturable.')
        : 'No capture produced.';
      out.push(`| **${screen.id}** ${esc(screen.name)} | _all_ | ${variants.map(() => 'n/a').join(' | ')} | — ${esc(why)} |`);
      continue;
    }
    const preferred = caps.get('1440-dark') || caps.get('1440-light') || [...caps.values()][0];
    const shot = preferred.screenshot ? `[png](${preferred.screenshot.split(path_sep()).join('/')})` : '—';
    for (const rule of rules) {
      const cells = variants.map(v => {
        const cap = caps.get(v.key);
        if (!cap) return '—';
        if (cap.error) return 'err';
        return ICON[verdict(rule, cap.rules[rule]).status] || '?';
      });
      out.push(`| **${screen.id}** ${esc(screen.name)} | ${rule} | ${cells.join(' | ')} | ${shot} |`);
    }
  }
  out.push('');

  // ── Findings ────────────────────────────────────────────────────────────
  out.push('## Findings, by rule');
  out.push('');

  // TOUCH-003
  out.push('### TOUCH-003 — hit regions under 44 pt');
  out.push('');
  const touchWorst = new Map();
  for (const r of results) {
    const d = r.rules['TOUCH-003'];
    if (!d || !d.worst) continue;
    for (const w of d.worst) {
      const key = signature(w.path);
      let e = touchWorst.get(key);
      if (!e) {
        e = { ...w, sig: key, instances: 0, screens: new Set(), variants: new Set(), labels: new Set() };
        touchWorst.set(key, e);
      }
      e.w = Math.min(e.w, w.w);
      e.h = Math.min(e.h, w.h);
      e.nested = e.nested && w.nested;
      e.instances++;
      e.screens.add(r.id);
      e.variants.add(r.variant);
      if (w.label) e.labels.add(w.label);
    }
  }
  if (touchWorst.size === 0) {
    out.push('No interactive element measured under 44 pt in any capture.');
  } else {
    out.push('Smallest first. `Nested` marks a target that sits inside a larger interactive ancestor —');
    out.push('recorded because the glyph is easier to hit than its size suggests, but not an exemption where');
    out.push('the two carry different actions.');
    out.push('');
    out.push('| Element | Example label | Smallest (pt) | Nested | Screens | Widths |');
    out.push('|---|---|---|:--:|---|---|');
    const rows = [...touchWorst.values()].sort((a, b) => a.w * a.h - b.w * b.h).slice(0, 45);
    for (const w of rows) {
      const label = [...w.labels][0] || '';
      const widths = [...new Set([...w.variants].map(v => v.split('-')[0]))].sort().join(', ');
      out.push(`| \`${esc(w.sig)}\` | ${esc(label) || '—'} | **${w.w} × ${w.h}** | ${w.nested ? 'yes' : 'no'} | ${[...w.screens].sort().slice(0, 10).join(', ')}${w.screens.size > 10 ? ` +${w.screens.size - 10}` : ''} | ${widths} |`);
    }
    if (touchWorst.size > 45) {
      out.push('');
      out.push(`_${touchWorst.size - 45} further distinct selectors omitted; the full list is in \`screenshots/results.json\`._`);
    }
  }
  out.push('');

  // ACCESS-008
  out.push('### ACCESS-008 — text below WCAG AA');
  out.push('');
  const contrastWorst = new Map();
  let indeterminate = 0;
  for (const r of results) {
    const d = r.rules['ACCESS-008'];
    if (!d) continue;
    indeterminate += d.indeterminate || 0;
    for (const w of (d.worst || [])) {
      const key = signature(w.path) + '|' + w.fg + '|' + w.bg;
      let e = contrastWorst.get(key);
      if (!e) {
        e = { ...w, sig: signature(w.path), screens: new Set(), variants: new Set(), texts: new Set() };
        contrastWorst.set(key, e);
      }
      e.ratio = Math.min(e.ratio, w.ratio);
      e.screens.add(r.id);
      e.variants.add(r.variant);
      if (w.text) e.texts.add(w.text);
    }
  }
  const pictoRows = [...contrastWorst.values()].filter(w => isPictographic([...w.texts][0] || ''));
  for (const w of pictoRows) contrastWorst.delete([...contrastWorst.entries()].find(([, v]) => v === w)[0]);

  if (contrastWorst.size === 0) {
    out.push('Every measured text node met its AA target in every capture.');
  } else {
    out.push('Worst ratio first. `Ratio` is the composited value — the declared colour after every translucent');
    out.push('fill and inherited `opacity` between the text and the first opaque surface has been applied.');
    out.push('');
    out.push('| Element | Example text | Ratio | Target | Font | Foreground | Composited background | Opacity | Themes | Screens |');
    out.push('|---|---|---:|---:|---|---|---|---:|---|---|');
    const rows = [...contrastWorst.values()].sort((a, b) => a.ratio - b.ratio).slice(0, 45);
    for (const w of rows) {
      const text = [...w.texts][0] || '';
      const themes = [...new Set([...w.variants].map(v => (v.endsWith('light') ? 'light' : 'dark')))].sort().join(' + ');
      out.push(`| \`${esc(w.sig)}\` | ${esc(text) || '—'} | **${w.ratio}** | ${w.target} | ${w.fontPx}px/${w.weight} | \`${esc(w.fg)}\` | \`${esc(w.bg)}\` | ${w.opacity} | ${themes} | ${[...w.screens].sort().slice(0, 8).join(', ')}${w.screens.size > 8 ? ` +${w.screens.size - 8}` : ''} |`);
    }
    if (contrastWorst.size > 45) {
      out.push('');
      out.push(`_${contrastWorst.size - 45} further distinct selector/colour pairs omitted; the full list is in \`screenshots/results.json\`._`);
    }
  }
  const phChecked = results.reduce((n, r) => n + ((r.rules['ACCESS-008'] || {}).placeholdersChecked || 0), 0);
  const phFailed = results.reduce((n, r) => n + ((r.rules['ACCESS-008'] || {}).placeholderFailures || 0), 0);
  if (pictoRows.length) {
    out.push('');
    const glyphs = [...new Set(pictoRows.map(w => [...w.texts][0]))];
    out.push('**Pictographic glyphs, measured but not counted.** ' + pictoRows.length + ' of the failing measurements are runs of '
      + 'pictographic characters (' + glyphs.map(g => '`' + esc(g) + '`').join(', ') + '), across the light and dark captures. Where '
      + 'these render as a colour bitmap the glyph paints its own pixels, so the computed `color` the ratio is derived from never '
      + 'reaches the screen and the number would be meaningless; they are excluded from the count above. What the measurement does show '
      + 'is the `opacity: 0.5` those glyphs carry: on monochrome text that halves the contrast, and on a colour bitmap it does not — '
      + 'which is exactly IMP-058\'s point about mixing the two icon families. Whether each of these actually renders in colour, and '
      + 'whether it is legible, needs an eye on the real machines (ICON-002 / ICON-005), not a ratio.');
  }
  if (phChecked) {
    out.push('');
    out.push(`**Placeholder text (INPUT-022).** ${phChecked} rendered placeholder measurements across all captures, `
      + `${phFailed} below AA. Placeholder colour is measured through \`getComputedStyle(el, '::placeholder')\`, so where `
      + 'no `::placeholder` rule exists this is the colour the user agent actually chose — the value no code read could supply.');
  }
  if (indeterminate) {
    out.push('');
    out.push(`${indeterminate} text node measurements were skipped as **indeterminate** — a \`background-image\` sits between the text and its backdrop, so a computed ratio would not be the ratio the eye receives. These need a human check.`);
  }
  out.push('');

  // LAYOUT-003
  out.push('### LAYOUT-003 / ACCESS-001 — horizontal overflow');
  out.push('');
  const overflowRows = results
    .filter(r => r.rules['LAYOUT-003/ACCESS-001'] && r.rules['LAYOUT-003/ACCESS-001'].overflowPx > 1)
    .map(r => ({ r, d: r.rules['LAYOUT-003/ACCESS-001'] }))
    .sort((a, b) => b.d.overflowPx - a.d.overflowPx);
  if (overflowRows.length === 0) {
    out.push('No capture overflowed the document horizontally, at any width, in either theme, or at 200% zoom.');
  } else {
    out.push('| Screen | Variant | Overflow | Viewport | Widest offender |');
    out.push('|---|---|---:|---:|---|');
    for (const { r, d } of overflowRows.slice(0, 40)) {
      const first = d.offenders[0];
      out.push(`| **${r.id}** ${esc(r.name)} | \`${r.variant}\` | ${d.overflowPx}px | ${d.viewport}px | ${first ? '`' + esc(first.path) + '` — right edge ' + first.right + 'px' : '—'} |`);
    }
    if (overflowRows.length > 40) {
      out.push('');
      out.push(`_${overflowRows.length - 40} further overflowing captures omitted; the full list is in \`screenshots/results.json\`._`);
    }
  }
  out.push('');

  // LAYOUT-011
  out.push('### LAYOUT-011 — actionable content behind a fixed bar');
  out.push('');
  const occRows = results
    .filter(r => r.rules['LAYOUT-011'] && r.rules['LAYOUT-011'].coveredCount > 0)
    .sort((a, b) => b.rules['LAYOUT-011'].coveredCount - a.rules['LAYOUT-011'].coveredCount);
  if (occRows.length === 0) {
    const barSample = results.find(r => r.rules['LAYOUT-011'] && r.rules['LAYOUT-011'].bars.length);
    const bars = barSample
      ? barSample.rules['LAYOUT-011'].bars.map(b => '`' + b.path + '` (' + b.anchor + ')').join(', ')
      : 'none';
    out.push('With every scroll region driven to its end, nothing actionable was found stuck behind a fixed or');
    out.push('sticky bar in any capture. Bars detected on the dashboard: ' + bars + '.');
  } else {
    out.push('| Screen | Variant | Covered | Example element | Covered by |');
    out.push('|---|---|---:|---|---|');
    for (const r of occRows.slice(0, 40)) {
      const d = r.rules['LAYOUT-011'];
      const first = d.covered[0];
      out.push(`| **${r.id}** ${esc(r.name)} | \`${r.variant}\` | ${d.coveredCount} | ${first ? '`' + esc(first.path) + '` ' + esc(first.label) : '—'} | ${first ? '`' + esc(first.blockedBy) + '`' : '—'} |`);
    }
  }
  const underTop = results.reduce((n, r) => n + ((r.rules['LAYOUT-011'] || {}).passUnderTopBar || 0), 0);
  const underTopCaptures = results.filter(r => ((r.rules['LAYOUT-011'] || {}).passUnderTopBar || 0) > 0).length;
  if (underTop) {
    out.push('');
    out.push(`For completeness: ${underTop} interactive elements across ${underTopCaptures} captures were overlapped by a **top-anchored** `
      + 'sticky bar at maximum scroll. Each was re-probed after being parked at 60% of the viewport and each came clear, so none is a '
      + 'LAYOUT-011 failure — a row passing under a sticky header is what a sticky header does. They are counted here so the pass above '
      + 'is not read as "no bar ever overlaps anything".');
  }
  out.push('');

  // LAYOUT-020
  out.push('### LAYOUT-020 — layout shift on refresh');
  out.push('');
  const trigCount = {};
  for (const r of results) {
    const d = r.rules['LAYOUT-020'];
    if (d && d.applicable) trigCount[d.trigger] = (trigCount[d.trigger] || 0) + 1;
  }
  const bgCaps = results.filter(r => (r.rules['LAYOUT-020'] || {}).trigger === 'background interval callback');
  const bgClean = bgCaps.filter(r => r.rules['LAYOUT-020'].cls === 0 && r.rules['LAYOUT-020'].moved === 0).length;
  out.push('**Read the trigger column before the CLS column.** Two different things were measured, and only one of them');
  out.push('is what LAYOUT-020 prohibits.');
  out.push('');
  out.push(`* **A real background timer fired** (${trigCount['background interval callback'] || 0} captures): the Recent Entries 60-second poll, the`);
  out.push('  Order Detail allocation-expiry countdown, and Process Flow\'s 60-second auto-refresh. These are exactly the');
  out.push(`  case the rule is about — content changing with no user action. **${bgClean} of ${bgCaps.length} recorded CLS 0 with nothing moved.**`);
  out.push('  Process Flow keeps its last good render and rewrites in place; the countdown rewrites text inside a fixed cell.');
  out.push('  On the evidence of this run the product has no background refresh that moves content under the user.');
  out.push(`* **The Refresh control was pressed** (${trigCount['#refresh-btn'] || 0} captures), because those screens have no timer of their own.`);
  out.push('  LAYOUT-020 permits layout change that is "a direct response to their explicit action", so a shift here is not a');
  out.push('  violation of the letter of the rule. It is reported because the same `refreshAll()` path runs unprompted at app');
  out.push('  start, and because it demonstrates the blank-and-repaint behaviour (SYS-2) that *would* violate the rule the');
  out.push('  moment any of these lists gains the auto-refresh IMP-036 proposes.');
  out.push('');
  out.push('`Anchors lost` counts elements whose identity key was absent after the refresh — destroyed outright, or re-keyed');
  out.push('because their ordinal position moved. It is a signal to look, not a finding on its own.');
  out.push('');
  const shiftRows = results
    .filter(r => {
      const d = r.rules['LAYOUT-020'];
      return d && d.applicable && (d.cls > 0.1 || d.moved > 0);
    })
    .sort((a, b) => b.rules['LAYOUT-020'].cls - a.rules['LAYOUT-020'].cls);
  if (shiftRows.length === 0) {
    out.push('No capture shifted on refresh: CLS 0 and no anchor moved in every applicable capture.');
  } else {
    out.push('| Screen | Variant | CLS | Moved | Max Δ | Anchors lost | Trigger | Worst mover |');
    out.push('|---|---|---:|---:|---:|---:|---|---|');
    for (const r of shiftRows.slice(0, 45)) {
      const d = r.rules['LAYOUT-020'];
      const w = d.worst && d.worst[0];
      out.push(`| **${r.id}** ${esc(r.name)} | \`${r.variant}\` | **${d.cls}** | ${d.moved} | ${d.maxDeltaPx}px | ${d.vanished} | ${esc(d.trigger)} | ${w ? esc(w.key) + ` (Δx ${w.dx}px, Δy ${w.dy}px)` : '—'} |`);
    }
    if (shiftRows.length > 45) {
      out.push('');
      out.push(`_${shiftRows.length - 45} further shifting captures omitted; the full list is in \`screenshots/results.json\`._`);
    }
  }
  out.push('');

  // ── Category 17 · Status & Data Display ─────────────────────────────────
  // Every STATUS finding is an element-level record with a `worst` array on the
  // rule's data. They differ only in which columns are worth printing, so one
  // aggregator handles all eight: collapse by signature (plus whatever second
  // key distinguishes two findings on the same selector), then print.
  const STATUS_SECTIONS = [
    {
      rule: 'STATUS-002',
      title: 'STATUS-002 — nominal values rendered as a badge',
      empty: 'No chip announced a nominal value in colour in any capture.',
      lead: ['A row where nothing is wrong should carry no badge. These do.'],
      columns: ['Chip', 'Text', 'Screens'],
      key: w => w.text || '',
      row: (e, screens) => [`\`${esc(e.sig)}\``, esc([...e.texts][0] || '—'), screens],
      collect: (e, w) => { (e.texts = e.texts || new Set()).add(w.text); },
    },
    {
      rule: 'STATUS-004',
      title: 'STATUS-004 — list rows carrying more than one alarm',
      empty: 'No list row carried more than one danger- or warning-toned element in any capture.',
      lead: [
        'Tone is measured by hue against the resolved `--danger` and `--warning` tokens, so a `color-mix()`ed',
        'fill counts as the token it was mixed from and a class rename does not hide it. Inherited text colour is',
        'attributed to the element that introduces it, not to every descendant that inherits it.',
      ],
      columns: ['Row', 'Most alarms seen', 'Tones', 'Screens'],
      key: () => '',
      row: (e, screens) => [`\`${esc(e.sig)}\``, `**${e.alarms}**`, esc([...e.tones].sort().join(', ')), screens],
      collect: (e, w) => {
        e.alarms = Math.max(e.alarms || 0, w.alarms || 0);
        e.tones = e.tones || new Set();
        for (const m of w.marks || []) e.tones.add(m.tone + ' (' + m.via + ')');
      },
      sort: (a, b) => (b.alarms || 0) - (a.alarms || 0),
      sigOf: w => w.row,
    },
    {
      rule: 'STATUS-005',
      title: 'STATUS-005 — chips with no explanation hook',
      empty: 'Every chip carried `data-explain`, an `aria-describedby` link and a focus stop.',
      lead: [
        'Expected to be the whole population until the redesign lands: the hook does not exist in the product yet.',
        'The `title=` column is the migration surface — a tooltip a touch device never shows, standing in for the',
        'popover the rule asks for.',
      ],
      columns: ['Chip', 'Example text', 'What is missing', 'Has `title=`', 'Screens'],
      key: w => w.reasons.join('+'),
      row: (e, screens) => [
        `\`${esc(e.sig)}\``, esc([...e.texts][0] || '—'),
        esc((e.reasons || []).join('; ')), e.hasTitle ? 'yes' : 'no', screens,
      ],
      collect: (e, w) => {
        (e.texts = e.texts || new Set()).add(w.text);
        e.reasons = w.reasons;
        e.hasTitle = e.hasTitle || w.hasTitle;
      },
    },
    {
      rule: 'STATUS-006',
      title: 'STATUS-006 — numbers outside the format',
      empty: 'Every rendered number matched the format.',
      lead: [
        '`raw-decimal` is a stored value that reached the screen; `no-separator` is a value of 1,000 or more written',
        'without a comma; `lb-precision` and `pallet-precision` are the wrong number of decimals for the unit;',
        '`not-tabular` is digits in an aligned column rendered with proportional figures, measured only where',
        'digit width can misalign the column — a separator, a decimal, a unit, or three or more digits — and',
        'outside any column whose header names an identifier. Codes, dates, bare years and identifier',
        'columns (SKU, Code, Lot, Order) are skipped throughout, so a numeric SKU is never counted as an',
        'unseparated quantity.',
      ],
      columns: ['Kind', 'Element', 'Example', 'Screens'],
      key: w => w.kind,
      row: (e, screens) => [`\`${esc(e.kind)}\``, `\`${esc(e.sig)}\``, esc([...e.samples][0] || '—'), screens],
      collect: (e, w) => {
        e.kind = w.kind;
        (e.samples = e.samples || new Set()).add(w.context || w.value);
      },
      sort: (a, b) => String(a.kind).localeCompare(String(b.kind)) || b.instances - a.instances,
      extra: results => {
        const kinds = {};
        for (const r of results) {
          const d = r.rules['STATUS-006'];
          for (const [k, n] of Object.entries((d && d.byKind) || {})) kinds[k] = (kinds[k] || 0) + n;
        }
        if (!Object.keys(kinds).length) return [];
        const lines = ['', '**Failures by kind, across all captures.**', '', '| Kind | Count |', '|---|---:|'];
        for (const [k, n] of Object.entries(kinds).sort((a, b) => b[1] - a[1])) lines.push(`| \`${k}\` | ${n} |`);
        return lines;
      },
    },
    {
      rule: 'STATUS-007',
      title: 'STATUS-007 — orphan placeholders',
      empty: 'No dash-only element was rendered outside a table cell.',
      lead: ['A dash inside a table cell holds the column\'s alignment and is the rule\'s stated exception; these are not that.'],
      columns: ['Element', 'Text', 'Screens'],
      key: w => w.text,
      row: (e, screens) => [`\`${esc(e.sig)}\``, esc([...e.texts][0] || '—'), screens],
      collect: (e, w) => { (e.texts = e.texts || new Set()).add(w.text); },
    },
    {
      rule: 'STATUS-008',
      title: 'STATUS-008 — list rows over 56 px at desktop width',
      empty: 'Every list row measured at or under 56 px at 1440 px.',
      lead: ['Tallest first. Measured only at viewports ≥ 1200 px; rows the user expanded are excluded.'],
      columns: ['Row', 'Tallest', 'Screens'],
      key: () => '',
      row: (e, screens) => [`\`${esc(e.sig)}\``, `**${e.height}px**`, screens],
      collect: (e, w) => { e.height = Math.max(e.height || 0, w.height || 0); },
      sort: (a, b) => (b.height || 0) - (a.height || 0),
    },
    {
      rule: 'STATUS-010',
      title: 'STATUS-010 — developer vocabulary in user-facing copy',
      empty: 'No denylisted term and no `snake_case` identifier appeared in any rendered text.',
      lead: ['Rendered text and the `title` / `placeholder` / `aria-label` copy that goes with it.'],
      columns: ['Term(s)', 'Element', 'Copy', 'Screens'],
      key: w => w.terms.join('+'),
      row: (e, screens) => [
        esc((e.terms || []).map(t => '`' + t + '`').join(', ')),
        `\`${esc(e.sig)}\``, esc([...e.texts][0] || '—'), screens,
      ],
      collect: (e, w) => { e.terms = w.terms; (e.texts = e.texts || new Set()).add(w.text); },
    },
    {
      rule: 'STATUS-011',
      title: 'STATUS-011 — sentences rendered more than once in one view',
      empty: 'No sentence of 40 characters or more was rendered twice within a single capture.',
      lead: ['`Most in one view` is the highest number of times the sentence appeared in a single capture.'],
      columns: ['Sentence', 'Most in one view', 'Screens'],
      key: w => w.text,
      row: (e, screens) => [esc([...e.texts][0] || '—'), `**${e.count}**`, screens],
      collect: (e, w) => { (e.texts = e.texts || new Set()).add(w.text); e.count = Math.max(e.count || 0, w.count || 0); },
      sort: (a, b) => (b.count || 0) - (a.count || 0),
      sigOf: w => w.text.slice(0, 60),
    },
  ];

  out.push('## Findings, category 17 — Status & Data Display');
  out.push('');
  out.push('Eight of the fourteen STATUS rules have a mechanical clause. STATUS-001, -003, -009, -012, -013 and -014');
  out.push('need someone to read the screen and are absent from this report entirely — they are not reported as passing.');
  out.push('');

  for (const section of STATUS_SECTIONS) {
    out.push(`### ${section.title}`);
    out.push('');
    const grouped = new Map();
    for (const r of results) {
      const d = r.rules[section.rule];
      if (!d || !d.worst) continue;
      for (const w of d.worst) {
        const sig = section.sigOf ? signature(section.sigOf(w)) : signature(w.path);
        const key = sig + '|' + section.key(w);
        let e = grouped.get(key);
        if (!e) { e = { sig, instances: 0, screens: new Set(), variants: new Set() }; grouped.set(key, e); }
        e.instances++;
        e.screens.add(r.id);
        e.variants.add(r.variant);
        section.collect(e, w);
      }
    }
    if (grouped.size === 0) {
      out.push(section.empty);
    } else {
      for (const line of section.lead) out.push(line);
      out.push('');
      out.push('| ' + section.columns.join(' | ') + ' | Instances |');
      out.push('|' + section.columns.map(() => '---').join('|') + '|---:|');
      const rows = [...grouped.values()].sort(section.sort || ((a, b) => b.instances - a.instances));
      for (const e of rows.slice(0, 40)) {
        const screens = [...e.screens].sort().slice(0, 8).join(', ') + (e.screens.size > 8 ? ` +${e.screens.size - 8}` : '');
        out.push('| ' + section.row(e, screens).join(' | ') + ` | ${e.instances} |`);
      }
      if (grouped.size > 40) {
        out.push('');
        out.push(`_${grouped.size - 40} further distinct findings omitted; the full list is in \`screenshots/results.json\`._`);
      }
    }
    if (section.extra) for (const line of section.extra(results)) out.push(line);
    // STATUS-005 carries one number the table cannot show: how many chips are
    // in scope at all, and how many of them lean on a `title` tooltip today.
    if (section.rule === 'STATUS-005') {
      const chips = results.reduce((n, r) => n + ((r.rules['STATUS-005'] || {}).checked || 0), 0);
      const titles = results.reduce((n, r) => n + ((r.rules['STATUS-005'] || {}).titleOnly || 0), 0);
      const complete = results.reduce((n, r) => n + ((r.rules['STATUS-005'] || {}).complete || 0), 0);
      out.push('');
      out.push(`**Scope.** ${chips} chip measurements across all captures; ${complete} carry the full hook, ${titles} carry a \`title\` attribute.`);
    }
    out.push('');
  }

  // ── Capture notes / errors ──────────────────────────────────────────────
  // Surfaces with no light palette at all — an ACCESS-001 observation this run settles.
  const unthemed = new Map();
  for (const r of results) {
    if (r.themeResponded === false) {
      if (!unthemed.has(r.page)) unthemed.set(r.page, new Set());
      unthemed.get(r.page).add(r.id);
    }
  }
  if (unthemed.size) {
    out.push('## Surfaces with no light palette');
    out.push('');
    out.push('Setting `data-theme="light"` on the root moved nothing on these pages: the painted background was identical');
    out.push('before and after. `dashboard/` carries a paired light/dark token set and responds; the other four surfaces do');
    out.push('not have a light mode to honour. Their "light" captures in the matrix above are therefore the same dark surface');
    out.push('as their dark captures, and their contrast results are one measurement reported twice — not two.');
    out.push('');
    out.push('| Surface | Screens | Effect on this run |');
    out.push('|---|---:|---|');
    for (const [page, ids] of unthemed) {
      out.push(`| \`${page}\` | ${ids.size} | light and dark captures are identical |`);
    }
    out.push('');
    out.push('This bears on ACCESS-001 ("support dark mode", "honor … light/dark settings") and on SYS-1: five `:root`');
    out.push('palettes, one of which is themed. It is not a new finding — IMP-010 and IMP-027 already own it — but it is now');
    out.push('measured rather than inferred.');
    out.push('');
  }

  const noted = results.filter(r => r.error || (r.notes && r.notes.length) || (r.consoleErrors && r.consoleErrors.length));
  out.push('## Capture notes');
  out.push('');
  if (!noted.length) {
    out.push('Every capture reached its target state cleanly, with no page error.');
  } else {
    out.push('| Screen | Variant | Note |');
    out.push('|---|---|---|');
    const seen = new Set();
    for (const r of noted) {
      const msgs = [];
      if (r.error) msgs.push('**capture error:** ' + r.error);
      for (const n of r.notes || []) msgs.push(n);
      for (const c of (r.consoleErrors || []).slice(0, 2)) msgs.push('console: `' + c + '`');
      const line = `| **${r.id}** | \`${r.variant}\` | ${esc(msgs.join(' · '))} |`;
      const key = r.id + msgs.join('');
      if (seen.has(key)) continue;
      seen.add(key);
      out.push(line);
    }
  }
  out.push('');

  const notCapturable = screens.filter(s => s.capturable === false);
  if (notCapturable.length) {
    out.push('### Screens that cannot be captured');
    out.push('');
    out.push('| Screen | Why |');
    out.push('|---|---|');
    for (const s of notCapturable) out.push(`| **${s.id}** ${esc(s.name)} | ${esc(s.note)} |`);
    out.push('');
    out.push('These four are the browser-native `confirm`/`alert` dialogs of SYS-7. The dialog is browser chrome:');
    out.push('nothing about it is in the document, so no rule here can be measured against it either way. That is');
    out.push('itself the argument for IMP-014/016/026/060 replacing them, but this run adds no evidence.');
    out.push('');
  }

  out.push('## Reproducing this');
  out.push('');
  out.push('```sh');
  out.push('npm install');
  out.push('npx playwright install chromium');
  out.push('npm run test:visual');
  out.push('```');
  out.push('');
  out.push('Narrow a run with `--screens S-25,S-42` or `--variants 1440-dark`, and watch it with `--headed`.');
  out.push('');
  out.push('---');
  out.push('');
  out.push('*Generated by `tests/visual/run-visual-audit.mjs`. Re-running regenerates this file in place.*');

  return out.join('\n') + '\n';
}

function path_sep() {
  return process.platform === 'win32' ? '\\' : '/';
}
